package model

import (
	"fmt"
)

type Application struct {
	ID               string
	Name             string
	Type             ApplicationType
	SubType          ApplicationSubType
	InternalAddress  string
	Site             string
	AccessPolicies   []string
	ActivityPolicies []string
	ToDelete         bool
}

func (a *Application) String() string {
	return fmt.Sprintf("%#v", a)
}

type ApplicationType string

const (
	DefaultType ApplicationType = "HTTP"
	HTTP                        = "HTTP"
	SSH                         = "SSH"
	RDP                         = "RDP"
	TCP                         = "TCP"
	DynamicSSH                  = "DYNAMIC_SSH"
)

func (a ApplicationType) String() string {
	return string(a)
}

type ApplicationSubType string

const (
	DefaultSubType      ApplicationSubType = "HTTP_LUMINATE_DOMAIN"
	AutoGeneratedDomain                    = "HTTP_LUMINATE_DOMAIN"
	CustomDomain                           = "HTTP_CUSTOM_DOMAIN"
	WildCardDomain                         = "HTTP_WILDCARD_DOMAIN"
	RdpSingleMachine                       = "SINGLE_MACHINE"
	RdpMultipleMachines                    = "MULTIPLE_MACHINES"
)

func (a ApplicationSubType) String() string {
	return string(a)
}
