package model

import (
	"fmt"
)

type CommonApplicationParams struct {
	Name                  string
	SiteName              string
	IsVisible             bool
	IsNotificationEnabled bool
	Enabled               bool
	AccessPoliciesNames   []string
	ActivityPoliciesNames []string
}

type ConnectionSettings struct {
	InternalAddress       string
	Subdomain             string
	CustomExternalAddress string
	CustomRootPath        string
	HealthUrl             string
	HealthMethod          string
	CustomSSLCertificate  string
	WildcardPrivateKey    string
}

type HttpLinkTranslationSettings struct {
	IsDefaultContentRewriteRulesEnabled bool
	IsDefaultHeaderRewriteRulesEnabled  bool
	UseExternalAddressForHostAndSni     bool
	LinkedApplications                  []string
}

type HttpRequestCustomizationSettings struct {
	HeaderCustomization map[string]string
}

type Application struct {
	ID       string
	Type     ApplicationType
	SubType  ApplicationSubType
	ToDelete bool

	CommonApplicationParams

	*ConnectionSettings
	*HttpLinkTranslationSettings
	*HttpRequestCustomizationSettings
}

func (a *Application) String() string {
	return fmt.Sprintf("%#v", a)
}

type ApplicationType string

const (
	DefaultType ApplicationType = "HTTP"
	HTTP                        = "HTTP"
	SSH                         = "SSH"
	RDP                         = "RDP"
	TCP                         = "TCP"
	DynamicSSH                  = "DYNAMIC_SSH"
)

func (a ApplicationType) String() string {
	return string(a)
}

type ApplicationSubType string

const (
	DefaultSubType      ApplicationSubType = "HTTP_LUMINATE_DOMAIN"
	AutoGeneratedDomain                    = "HTTP_LUMINATE_DOMAIN"
	CustomDomain                           = "HTTP_CUSTOM_DOMAIN"
	WildCardDomain                         = "HTTP_WILDCARD_DOMAIN"
	RdpSingleMachine                       = "SINGLE_MACHINE"
	RdpMultipleMachines                    = "MULTIPLE_MACHINES"
)

func (a ApplicationSubType) String() string {
	return string(a)
}
