package model

import (
	"fmt"
	"github.com/google/uuid"
)

type Application struct {
	ID               *uuid.UUID
	Name             string
	Type             ApplicationType
	SubType          ApplicationSubType
	InternalAddress  string
	Site             string
	AccessPolicies   []string
	ActivityPolicies []string
}

func (a *Application) String() string {
	return fmt.Sprintf("%#v", a)
}

type ApplicationType string

const (
	DefaultType ApplicationType = "HTTP"
	HTTP                        = "HTTP"
	SSH                         = "SSH"
	RDP                         = "RDP"
	TCP                         = "TCP"
	DynamicSSH                  = "DYNAMIC_SSH"
)

func (a ApplicationType) String() string {
	return a.String()
}

type ApplicationSubType string

const (
	DefaultSubType      ApplicationSubType = "HTTP_LUMINATE_DOMAIN"
	AutoGeneratedDomain                    = "HTTP_LUMINATE_DOMAIN"
	CustomDomain                           = "HTTP_CUSTOM_DOMAIN"
	WildCardDomain                         = "HTTP_WILDCARD_DOMAIN"
	RdpSingleMachine                       = "SINGLE_MACHINE"
	RdpMultipleMachines                    = "MULTIPLE_MACHINES"
)

func (a ApplicationSubType) String() string {
	return a.String()
}
