version: 2.1

commands: # a reusable command with parameters
  build_setup:
    steps:
      - run:
          name: docker setup
          command: |
            docker login --username ${OCI_IMAGE_REGISTRY_USERNAME} --password ${OCI_IMAGE_REGISTRY_PASSWORD} ${OCI_IMAGE_REGISTRY_HOST_NAME}

jobs:
  test:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - run: make test
  build-push:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker
      - build_setup
      - run: make docker-build
      - run: make docker-push

workflows:
  build-and-push:
    jobs:
      - test
      - build-push:
          filters:
            branches:
              only:
                - master
          context: public-artifacts
          requires:
            - test