# permissions for end users to view httpapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httpapplication-viewer-role
rules:
- apiGroups:
  - access.secure-access-cloud.symantec.com
  resources:
  - httpapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - access.secure-access-cloud.symantec.com
  resources:
  - httpapplications/status
  verbs:
  - get
