
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - access.secure-access-cloud.symantec.com
  resources:
  - httpapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - access.secure-access-cloud.symantec.com
  resources:
  - httpapplications/finalizers
  verbs:
  - update
- apiGroups:
  - access.secure-access-cloud.symantec.com
  resources:
  - httpapplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - access.secure-access-cloud.symantec.com
  resources:
  - sites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - access.secure-access-cloud.symantec.com
  resources:
  - sites/finalizers
  verbs:
  - update
- apiGroups:
  - access.secure-access-cloud.symantec.com
  resources:
  - sites/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
