# permissions for end users to edit sites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: site-editor-role
rules:
- apiGroups:
  - access.secure-access-cloud.symantec.com
  resources:
  - sites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - access.secure-access-cloud.symantec.com
  resources:
  - sites/status
  verbs:
  - get
