//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonApplicationParams) DeepCopyInto(out *CommonApplicationParams) {
	*out = *in
	if in.AccessPoliciesNames != nil {
		in, out := &in.AccessPoliciesNames, &out.AccessPoliciesNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ActivityPoliciesNames != nil {
		in, out := &in.ActivityPoliciesNames, &out.ActivityPoliciesNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IsVisible != nil {
		in, out := &in.IsVisible, &out.IsVisible
		*out = new(bool)
		**out = **in
	}
	if in.IsNotificationEnabled != nil {
		in, out := &in.IsNotificationEnabled, &out.IsNotificationEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonApplicationParams.
func (in *CommonApplicationParams) DeepCopy() *CommonApplicationParams {
	if in == nil {
		return nil
	}
	out := new(CommonApplicationParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonApplicationStatus) DeepCopyInto(out *CommonApplicationStatus) {
	*out = *in
	in.ModifiedOn.DeepCopyInto(&out.ModifiedOn)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonApplicationStatus.
func (in *CommonApplicationStatus) DeepCopy() *CommonApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(CommonApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpApplication) DeepCopyInto(out *HttpApplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpApplication.
func (in *HttpApplication) DeepCopy() *HttpApplication {
	if in == nil {
		return nil
	}
	out := new(HttpApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HttpApplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpApplicationList) DeepCopyInto(out *HttpApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HttpApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpApplicationList.
func (in *HttpApplicationList) DeepCopy() *HttpApplicationList {
	if in == nil {
		return nil
	}
	out := new(HttpApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HttpApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpApplicationSpec) DeepCopyInto(out *HttpApplicationSpec) {
	*out = *in
	in.CommonApplicationParams.DeepCopyInto(&out.CommonApplicationParams)
	out.Service = in.Service
	if in.HttpConnectionSettings != nil {
		in, out := &in.HttpConnectionSettings, &out.HttpConnectionSettings
		*out = new(HttpConnectionSettings)
		**out = **in
	}
	if in.HttpLinkTranslationSettings != nil {
		in, out := &in.HttpLinkTranslationSettings, &out.HttpLinkTranslationSettings
		*out = new(HttpLinkTranslationSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.HttpRequestCustomizationSettings != nil {
		in, out := &in.HttpRequestCustomizationSettings, &out.HttpRequestCustomizationSettings
		*out = new(HttpRequestCustomizationSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpApplicationSpec.
func (in *HttpApplicationSpec) DeepCopy() *HttpApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(HttpApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpConnectionSettings) DeepCopyInto(out *HttpConnectionSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpConnectionSettings.
func (in *HttpConnectionSettings) DeepCopy() *HttpConnectionSettings {
	if in == nil {
		return nil
	}
	out := new(HttpConnectionSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpLinkTranslationSettings) DeepCopyInto(out *HttpLinkTranslationSettings) {
	*out = *in
	if in.IsDefaultContentRewriteRulesEnabled != nil {
		in, out := &in.IsDefaultContentRewriteRulesEnabled, &out.IsDefaultContentRewriteRulesEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsDefaultHeaderRewriteRulesEnabled != nil {
		in, out := &in.IsDefaultHeaderRewriteRulesEnabled, &out.IsDefaultHeaderRewriteRulesEnabled
		*out = new(bool)
		**out = **in
	}
	if in.UseExternalAddressForHostAndSni != nil {
		in, out := &in.UseExternalAddressForHostAndSni, &out.UseExternalAddressForHostAndSni
		*out = new(bool)
		**out = **in
	}
	if in.LinkedApplications != nil {
		in, out := &in.LinkedApplications, &out.LinkedApplications
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpLinkTranslationSettings.
func (in *HttpLinkTranslationSettings) DeepCopy() *HttpLinkTranslationSettings {
	if in == nil {
		return nil
	}
	out := new(HttpLinkTranslationSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpRequestCustomizationSettings) DeepCopyInto(out *HttpRequestCustomizationSettings) {
	*out = *in
	if in.HeaderCustomization != nil {
		in, out := &in.HeaderCustomization, &out.HeaderCustomization
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpRequestCustomizationSettings.
func (in *HttpRequestCustomizationSettings) DeepCopy() *HttpRequestCustomizationSettings {
	if in == nil {
		return nil
	}
	out := new(HttpRequestCustomizationSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Service) DeepCopyInto(out *Service) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service.
func (in *Service) DeepCopy() *Service {
	if in == nil {
		return nil
	}
	out := new(Service)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Site) DeepCopyInto(out *Site) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Site.
func (in *Site) DeepCopy() *Site {
	if in == nil {
		return nil
	}
	out := new(Site)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Site) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteList) DeepCopyInto(out *SiteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Site, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteList.
func (in *SiteList) DeepCopy() *SiteList {
	if in == nil {
		return nil
	}
	out := new(SiteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteSpec) DeepCopyInto(out *SiteSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteSpec.
func (in *SiteSpec) DeepCopy() *SiteSpec {
	if in == nil {
		return nil
	}
	out := new(SiteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteStatus) DeepCopyInto(out *SiteStatus) {
	*out = *in
	if in.HealthyConnectors != nil {
		in, out := &in.HealthyConnectors, &out.HealthyConnectors
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.UnHealthyConnectors != nil {
		in, out := &in.UnHealthyConnectors, &out.UnHealthyConnectors
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteStatus.
func (in *SiteStatus) DeepCopy() *SiteStatus {
	if in == nil {
		return nil
	}
	out := new(SiteStatus)
	in.DeepCopyInto(out)
	return out
}
